### PR TITLE
Update spritesheet to include new Swampy Shores prop

### PR DESCRIPTION
**Pull request by akanecco23**
A new prop was added in the Swampy Shores update. Attempting to asset swap the new spritesheet to the one in Doctorpus Assets will result in the PIXI.JS spritesheet loader throwing an error. This is due to a mismatch between the dimensions of the spritesheet and the dimensions specified in the accompanying JSON file.

### CODE REVIEW

**Comment by SirReadsALot** [comment]
How did you try to asset swap the new spritesheet?

**Comment by akanecco23** [comment]
> How did you try to asset swap the new spritesheet?

I used [The-Doctorpus/doc-assets-extension](https://github.com/The-Doctorpus/doc-assets-extension) to asset swap.

**Comment by akanecco23** [comment]
Hello @SirReadsALot, here is a rewritten version of the Doctorpus Asset Chrome extension that is compliant with Manifest V3
https://github.com/The-Doctorpus/doc-assets-extension/pull/1

**Review by The-Doctorpus — APPROVED** [review]
Approved as a temporary fix to keep the extension functional.

**Pull request merged**
